In [47]:
%reload_ext autoreload
%autoreload 2

import numpy as np
import meshcat

from estimate_door_angle import GetDoorPose
from perception_tools.visualization_utils import *

In [2]:
vis = meshcat.Visualizer()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7001/static/


In [48]:
model_left_door = np.load("models/left_door_model.npy")
model_right_door = np.load("models/right_door_model.npy")

In [63]:
# Calculate the pose of the brick in the simulation
X_WLDoor, X_WRDoor = GetDoorPose("config/sim.yml", viz=True, left_door_angle=1.308996939)
print X_WLDoor, X_WRDoor

[[ 0.25501499 -0.96693339  0.          0.08048135]
 [ 0.96693339  0.25501499  0.         -0.62138797]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]] [[ 1.         -0.          0.         -0.74066833]
 [ 0.          1.          0.          0.14492425]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [64]:
# load and visualize the total aligned scene points
scene_points = np.load("saved_point_clouds/aligned_scene_points_left_door.npy")
scene_colors = np.load("saved_point_clouds/aligned_scene_colors_left_door.npy")
PlotMeshcatPointCloud(vis, "scene", scene_points, scene_colors)

In [65]:
# load and visualize the segmented brick points and the guess of the
# pose of the brick
left_door_points = np.load("saved_point_clouds/segmented_scene_points_left_door.npy")
left_door_colors = np.load("saved_point_clouds/segmented_scene_colors_left_door.npy")
right_door_points = np.load("saved_point_clouds/segmented_scene_points_right_door.npy")
right_door_colors = np.load("saved_point_clouds/segmented_scene_colors_right_door.npy")

PlotMeshcatPointCloud(vis, "left_door", left_door_points, left_door_colors)
PlotMeshcatPointCloud(vis, "right_door", right_door_points, right_door_colors)
VisualizeTransform(vis, model_left_door, X_WLDoor.inverse().matrix())
# VisualizeTransform(vis, model_right_door, X_WRDoor.inverse().matrix())

In [ ]:
# load and visualize the raw point clouds from each camera
leftcam_left_door_points = np.load("saved_point_clouds/left_points_left_door.npy")
leftcam_left_door_colors = np.load("saved_point_clouds/left_colors_left_door.npy")
PlotMeshcatPointCloud(vis, "leftcam_left_door_points", left_points, left_colors)

middle_points = np.load("saved_point_clouds/middle_points.npy")
middle_colors = np.load("saved_point_clouds/middle_colors.npy")
PlotMeshcatPointCloud(vis, "middle_points", middle_points, middle_colors)

right_points = np.load("saved_point_clouds/right_points.npy")
right_colors = np.load("saved_point_clouds/right_colors.npy")
PlotMeshcatPointCloud(vis, "right_points", right_points, right_colors)

In [ ]:
# clear everything
vis.delete()