In [1]:
%reload_ext autoreload
%autoreload 2

import numpy as np
import meshcat

from estimate_door_angle import GetDoorPose, get_door_angle
from perception_tools.visualization_utils import *
from pydrake.common.eigen_geometry import Isometry3

In [2]:
vis = meshcat.Visualizer()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/


In [3]:
is_planner_models = False
basepath = "../plan_runner/" if is_planner_models else ""

In [4]:
model_left_door = np.load("models/left_door_model.npy")
model_right_door = np.load("models/right_door_model.npy")

In [5]:
# Calculate the pose of the brick in the simulation
isometries = GetDoorPose("config/sim.yml", viz=True, left_door_angle=0.52, right_door_angle=0.52)
X_WLDoor = isometries["left_door"][0]
X_WRDoor = isometries["right_door"][0]
print X_WLDoor
print X_WRDoor
print X_WLDoor.inverse()
print X_WRDoor.inverse()
print get_door_angle(X_WLDoor)
print get_door_angle(X_WRDoor, flip_sign=True)

[[ 0.86717124 -0.49800802  0.         -0.49876164]
 [ 0.49800802  0.86717124  0.         -0.4520682 ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.8679843   0.4965829   0.         -0.4994646 ]
 [-0.4965829   0.8679843   0.          0.47771431]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.86717124  0.49800802  0.          0.65764534]
 [-0.49800802  0.86717124  0.          0.14363325]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.8679843  -0.4965829   0.          0.67075219]
 [ 0.4965829   0.8679843   0.         -0.16662295]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
0.5213025259275126
0.5196675799705425


In [6]:
# load and visualize the total aligned scene points
scene_points = np.load(basepath + "saved_point_clouds/aligned_scene_points_left_door.npy")
scene_colors = np.load(basepath + "saved_point_clouds/aligned_scene_colors_left_door.npy")
PlotMeshcatPointCloud(vis, "scene", scene_points, scene_colors)

In [7]:
# load and visualize the segmented brick points and the guess of the
# pose of the brick
left_door_points = np.load(basepath + "saved_point_clouds/segmented_scene_points_left_door.npy")
left_door_colors = np.load(basepath + "saved_point_clouds/segmented_scene_colors_left_door.npy")
right_door_points = np.load(basepath + "saved_point_clouds/segmented_scene_points_right_door.npy")
right_door_colors = np.load(basepath + "saved_point_clouds/segmented_scene_colors_right_door.npy")

PlotMeshcatPointCloud(vis, "left_door", left_door_points, left_door_colors)
PlotMeshcatPointCloud(vis, "right_door", right_door_points, right_door_colors)
VisualizeTransform(vis, model_left_door, X_WLDoor.inverse().matrix(), name="left_door_transform")
VisualizeTransform(vis, model_right_door, X_WRDoor.inverse().matrix(), name="right_door_transform")

In [ ]:
# load and visualize the raw point clouds from each camera
leftcam_left_door_points = np.load(basepath + "saved_point_clouds/left_points_left_door.npy")
leftcam_left_door_colors = np.load(basepath + "saved_point_clouds/left_colors_left_door.npy")
PlotMeshcatPointCloud(vis, "leftcam_left_door_points", left_points, left_colors)

middle_points = np.load(basepath + "saved_point_clouds/middle_points.npy")
middle_colors = np.load(basepath + "saved_point_clouds/middle_colors.npy")
PlotMeshcatPointCloud(vis, "middle_points", middle_points, middle_colors)

right_points = np.load(basepath + "saved_point_clouds/right_points.npy")
right_colors = np.load(basepath + "saved_point_clouds/right_colors.npy")
PlotMeshcatPointCloud(vis, "right_points", right_points, right_colors)

In [15]:
# clear everything
vis.delete()