In [1]:
%reload_ext autoreload
%autoreload 2

import numpy as np
import meshcat

from estimate_door_angle import GetDoorPose
from perception_tools.visualization_utils import *

In [2]:
vis = meshcat.Visualizer()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7001/static/


In [9]:
model_left_door = np.load("models/left_door_model.npy")
model_right_door = np.load("models/right_door_model.npy")

In [19]:
# Calculate the pose of the brick in the simulation
isometries = GetDoorPose("config/station_1.yml", viz=True)
X_WLDoor = isometries["left_door"][0]
X_WRDoor = isometries["right_door"][0]
print X_WLDoor, X_WRDoor

[[ 0.55350139 -0.83284825  0.         -0.19425642]
 [ 0.83284825  0.55350139  0.         -0.63551607]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]] [[ 0.9991639   0.04081485  0.         -0.77589893]
 [-0.04081485  0.9991639   0.          0.13840015]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [20]:
# load and visualize the total aligned scene points
scene_points = np.load("saved_point_clouds/aligned_scene_points_left_door.npy")
scene_colors = np.load("saved_point_clouds/aligned_scene_colors_left_door.npy")
PlotMeshcatPointCloud(vis, "scene", scene_points, scene_colors)

In [21]:
# load and visualize the segmented brick points and the guess of the
# pose of the brick
left_door_points = np.load("saved_point_clouds/segmented_scene_points_left_door.npy")
left_door_colors = np.load("saved_point_clouds/segmented_scene_colors_left_door.npy")
right_door_points = np.load("saved_point_clouds/segmented_scene_points_right_door.npy")
right_door_colors = np.load("saved_point_clouds/segmented_scene_colors_right_door.npy")

PlotMeshcatPointCloud(vis, "left_door", left_door_points, left_door_colors)
PlotMeshcatPointCloud(vis, "right_door", right_door_points, right_door_colors)
VisualizeTransform(vis, model_left_door, X_WLDoor.inverse().matrix())
# VisualizeTransform(vis, model_right_door, X_WRDoor.inverse().matrix())

In [ ]:
# load and visualize the raw point clouds from each camera
leftcam_left_door_points = np.load("saved_point_clouds/left_points_left_door.npy")
leftcam_left_door_colors = np.load("saved_point_clouds/left_colors_left_door.npy")
PlotMeshcatPointCloud(vis, "leftcam_left_door_points", left_points, left_colors)

middle_points = np.load("saved_point_clouds/middle_points.npy")
middle_colors = np.load("saved_point_clouds/middle_colors.npy")
PlotMeshcatPointCloud(vis, "middle_points", middle_points, middle_colors)

right_points = np.load("saved_point_clouds/right_points.npy")
right_colors = np.load("saved_point_clouds/right_colors.npy")
PlotMeshcatPointCloud(vis, "right_points", right_points, right_colors)

In [ ]:
# clear everything
vis.delete()